stages:
  - build
  - lint
  - test
  - security
  - review
  - deploy
  - dast

# Estágio de Build
build:
  stage: build
  script:
    - echo "Starting build process..."
    # Adicione seus comandos de construção específicos aqui, se necessário

# Estágio de Análise Estática de Código (SAST) com Bandit
lint:
  stage: lint
  image: python:3.9
  script:
    - pip install --upgrade pip
    - pip install bandit
    - bandit -r todo_project/todo_project -f html -o bandit-report.html || true
  artifacts:
    paths:
      - bandit-report.html
    expire_in: 1 week

# Estágio de Análise de Dependência com OWASP Dependency-Check
dependency_check:
  stage: security
  image: owasp/dependency-check:latest
  script:
    - dependency-check.sh --project "My Project" --scan todo_project/todo_project --out dependency-check-report.html
  artifacts:
    paths:
      - dependency-check-report.html
    expire_in: 1 week
  allow_failure: true

# Estágio de Testes
test:
  stage: test
  image: python:3.9
  cache:
    paths:
      - .cache/pip
  before_script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - pytest --maxfail=1 --disable-warnings -q

# Estágio de Deploy
deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
    # Adicione seus comandos de deploy aqui

# Estágio de Revisão
review:
  stage: review
  script:
    - echo "Creating review environment..."
    # Adicione seus comandos para criar o ambiente de revisão aqui

# Estágio de Testes de Segurança de Aplicação Dinâmicos (DAST)
dast:
  stage: dast
  image: owasp/zap2docker-stable
  script:
    - echo "Starting OWASP ZAP for DAST..."
    - zap-baseline.py -t http://localhost:8080 -r zap-report.html
  artifacts:
    paths:
      - zap-report.html
    expire_in: 1 week
