stages:
  - build
  - test

build:
  stage: build
  script:
    - echo "Build stage completed."

test:
  stage: test
  image: python:3.9
  script:
    - pip install -r requirements.txt
    - pytest --maxfail=1 --disable-warnings -q

