stages:
  - test

image: python:3.9

cache:
  paths:
    - .cache/pip/

before_script:
  - python -m venv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

test:
  stage: test
  script:
    - pytest
