image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  FLASK_APP: todo_project/run.py
  FLASK_ENV: development

stages:
  - build
  - test
  - scan

build:
  stage: build
  script:
    - docker build -t task-manager-flask .

test:
  stage: test
  script:
    - docker run --rm -p 5000:5000 task-manager-flask

zap-scan:
  stage: scan
  image: owasp/zap2docker-stable
  services:
    - name: owasp/zap2docker-stable
      alias: zap
  script:
    - >
      docker run -v $(pwd)/zap_data:/zap/wrk -t owasp/zap2docker-stable zap-baseline.py -t http://task-manager:5000 -r /zap/wrk/zap_report.html
  artifacts:
    paths:
      - zap_data/zap_report.html

