image: python:3.9

stages:
  - build
  - test

variables:
  VENV_DIR: venv

before_script:
  - python -m venv $VENV_DIR
  - source $VENV_DIR/bin/activate
  - pip install --upgrade pip
  - pip install -r requirements.txt

build:
  stage: build
  script:
    - echo "Build stage completed."

test:
  stage: test
  script:
    - source $VENV_DIR/bin/activate
    - pytest --maxfail=1 --disable-warnings -q
