stages:
  - test

image: python:3.9

# Instalação e configuração do ambiente
before_script:
  - python -m venv venv                       # Cria ambiente virtual
  - source venv/bin/activate                  # Ativa ambiente virtual
  - pip install --upgrade pip                 # Atualiza pip
  - pip install pytest                        # Instala pytest

# Job de teste simples
test:
  stage: test
  script:
    - pytest --maxfail=1 --disable-warnings -q   # Roda testes com pytest
