[[runners]]
  name = "docker-runner"
  url = "https://gitlab.com/"
  token = "glrt--QnuwtjZxej1LzCiHJWY"
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "ruby:3.1"
    privileged = true
