[[runners]]
  name = "docker-runner"
  url = "https://gitlab.com/"
  token = "glrt-njLa4MWpNxp3Um7EQGWZ"
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "my-app-image"  # Imagem Docker local
    privileged = true
    pull_policy = "if-not-present"  # Evita puxar a imagem se estiver disponível localmente

