version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - default

  zap:
    image: zaproxy/zap-stable:2.15.0
    ports:
      - "8081:8080"
    volumes:
      - ./zap_data:/zap/wrk
    command: zap.sh -daemon -host 0.0.0.0 -port 8080
    networks:
      - default

  db:
    image: postgres
    networks:
      - default

networks:
  default:
    driver: bridge

