version: '3'
services:
  zap:
    image: zaproxy/zap-stable:2.15.0
    ports:
      - "8080:8080"
    volumes:
      - ./zap_data::/zap/wrk
    command: zap-baseline.py -t https://a2ff-24-152-27-101.ngrok-free.app/ -r /zap/wrk/scan-report.html

