version: '3.8'

services:
  zap:
    image: minha_imagem_zap
    container_name: my_zap_container
    ports:
      - "8080:8080"
    volumes:
      - ./zap_data:/zap/wrk  # Verifique este caminho
    entrypoint: ["/zap/zap.sh", "-daemon", "-host", "0.0.0.0"]

