auth_enabled: false

server:
  http_listen_port: 3100

ingester:
  chunk_target_size: 1048576
  max_chunk_age: 1h
  max_chunk_idle: 5m

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
    shared_store: filesystem

  filesystem:
    directory: /loki/chunks

limits_config:
  ingestion_rate_mb: 5
  ingestion_burst_size_mb: 10
  max_cache_size_mb: 500

schema_config:
  configs:
  - from: 2020-10-24
    store: boltdb-shipper
    object_store: filesystem
    schema: v11
    index:
      prefix: index_
      period: 24h

ruler:
  enable: true
  storage:
    boltdb:
      directory: /ruler

frontend:
  compress_responses: true
  downstream_url: http://localhost:3100

  # Set this if you're using a separate Loki instance to avoid TLS certificate errors
  # url: http://loki:3100

